# Outreach and Teaching

## Cambridge University Astronomical Society (CUAS)
I was elected the Observation Secretary for the Cambridge University Astronomical Society for two terms (2022-2024). I operated the telescopes in the observatory, conducted training sessions and certified members to use the 190-year-old Northumberland Telescope. I also conducted several public stargazing nights, including one at a primary school in a nearby town.

## Assistant Physics Teacher
I gained experience as an assistant Physics teacher for Year 9 GCSE students at a local secondary school in Cambridge. I wrote a report titled “The effects of Inquiry-based learning on Physics Education” based on the outcome of my designed lesson.

## Volunteer at Science Fairs
I have presented experiments at the Cambridge Hands-On Science fairs to school children on topics including robotics, polarisation, air pressure, scattering, and infrared light. I have also volunteered for the Sussex Astronomy department’s stall at the Lewes STEM Fair and presented our astronomy research to the public.

## Programming Instructor for primary school
I taught MIT's block-based programming language ‘Scratch’ to Year 4 students at public schools in Oslo. I conducted the lessons in Norwegian and received pedagogical training from the Oslo Education Department (Utdanningsetaten).